apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    email: ngocdiemdo04@gmail.com  # ✅ Sửa email của bạn
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cloudflare-account-key
    solvers:
    - dns01:
        cloudflare:
          #email: ngocdiemdo04@gmail.com  # ✅ Không bắt buộc nếu dùng API token
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
